# Generated by Django 5.2.5 on 2025-10-23 18:50

import django.db.models.deletion
import rgs_django_utils.database.dj_extended_models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rgs_django_utils", "0003_enumaccessthrough"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnumMapAuthType",
            fields=[
                (
                    "id",
                    rgs_django_utils.database.dj_extended_models.TextStringField(
                        primary_key=True, serialize=False, verbose_name="code"
                    ),
                ),
                ("name", rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name="name")),
            ],
            options={
                "verbose_name": "map authentication type",
                "verbose_name_plural": "map authentication types",
                "db_table": "enum_map_auth_type",
            },
        ),
        migrations.CreateModel(
            name="EnumMapSourceType",
            fields=[
                (
                    "id",
                    rgs_django_utils.database.dj_extended_models.TextStringField(
                        primary_key=True, serialize=False, verbose_name="code"
                    ),
                ),
                ("name", rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name="name")),
            ],
            options={
                "verbose_name": "map source type",
                "verbose_name_plural": "map source types",
                "db_table": "enum_map_source_type",
            },
        ),
        migrations.CreateModel(
            name="SpatialStyle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name="naam")),
                (
                    "notes",
                    rgs_django_utils.database.dj_extended_models.TextStringField(
                        blank=True, null=True, verbose_name="opmerkingen"
                    ),
                ),
                (
                    "style_config",
                    rgs_django_utils.database.dj_extended_models.JSONField(verbose_name="stijl configuratie"),
                ),
            ],
            options={
                "verbose_name": "kaart stijl",
                "verbose_name_plural": "kaart stijlen",
                "db_table": "spatial_style",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EnumMapAuthTypeExtended",
            fields=[
                ("name", rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name="name")),
                (
                    "config_fields",
                    rgs_django_utils.database.dj_extended_models.ArrayField(
                        base_field=rgs_django_utils.database.dj_extended_models.TextStringField(), size=None
                    ),
                ),
                (
                    "id",
                    rgs_django_utils.database.dj_extended_models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="extended",
                        serialize=False,
                        to="rgs_django_spatial.enummapauthtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "map authentication type",
                "verbose_name_plural": "map authentication types",
                "db_table": "enum_map_auth_type_ext",
            },
        ),
        migrations.CreateModel(
            name="EnumMapSourceTypeExtended",
            fields=[
                ("name", rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name="name")),
                (
                    "config_fields",
                    rgs_django_utils.database.dj_extended_models.ArrayField(
                        base_field=rgs_django_utils.database.dj_extended_models.TextStringField(), size=None
                    ),
                ),
                (
                    "id",
                    rgs_django_utils.database.dj_extended_models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="extended",
                        serialize=False,
                        to="rgs_django_spatial.enummapsourcetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "map source type",
                "verbose_name_plural": "map source types",
                "db_table": "enum_map_source_type_ext",
            },
        ),
        migrations.CreateModel(
            name="SpatialLayer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name="naam")),
                (
                    "description",
                    rgs_django_utils.database.dj_extended_models.TextStringField(
                        blank=True, null=True, verbose_name="omschrijving"
                    ),
                ),
                (
                    "icon",
                    rgs_django_utils.database.dj_extended_models.TextStringField(
                        blank=True, null=True, verbose_name="icoon"
                    ),
                ),
                (
                    "access_id",
                    rgs_django_utils.database.dj_extended_models.IntegerField(
                        blank=True, null=True, verbose_name="toegang id"
                    ),
                ),
                (
                    "source_layer",
                    rgs_django_utils.database.dj_extended_models.TextStringField(
                        blank=True, null=True, verbose_name="laag in bron"
                    ),
                ),
                (
                    "params",
                    rgs_django_utils.database.dj_extended_models.JSONField(
                        blank=True, null=True, verbose_name="parameters"
                    ),
                ),
                (
                    "geometry_type",
                    rgs_django_utils.database.dj_extended_models.TextStringField(
                        blank=True, null=True, verbose_name="geometrie type"
                    ),
                ),
                (
                    "extent",
                    rgs_django_utils.database.dj_extended_models.ArrayField(
                        base_field=rgs_django_utils.database.dj_extended_models.FloatField(),
                        blank=True,
                        null=True,
                        size=4,
                        verbose_name="extent",
                    ),
                ),
                (
                    "min_zoom",
                    rgs_django_utils.database.dj_extended_models.IntegerField(
                        blank=True, null=True, verbose_name="min zoom"
                    ),
                ),
                (
                    "max_zoom",
                    rgs_django_utils.database.dj_extended_models.IntegerField(
                        blank=True, null=True, verbose_name="max zoom"
                    ),
                ),
                (
                    "license",
                    rgs_django_utils.database.dj_extended_models.TextStringField(
                        blank=True, null=True, verbose_name="licentie"
                    ),
                ),
                (
                    "refresh_interval",
                    rgs_django_utils.database.dj_extended_models.IntegerField(
                        blank=True, null=True, verbose_name="verversingsinterval"
                    ),
                ),
                (
                    "access_through",
                    rgs_django_utils.database.dj_extended_models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rgs_django_utils.enumaccessthrough",
                        verbose_name="toegang via",
                    ),
                ),
            ],
            options={
                "verbose_name": "kaartlaag",
                "verbose_name_plural": "kaartlagen",
                "db_table": "spatial_layer",
            },
        ),
        migrations.CreateModel(
            name="SpatialMap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name="naam")),
                (
                    "description",
                    rgs_django_utils.database.dj_extended_models.TextStringField(
                        blank=True, null=True, verbose_name="omschrijving"
                    ),
                ),
                (
                    "icon",
                    rgs_django_utils.database.dj_extended_models.TextStringField(
                        blank=True, null=True, verbose_name="icoon"
                    ),
                ),
                (
                    "order_index",
                    rgs_django_utils.database.dj_extended_models.IntegerField(
                        default=0, verbose_name="volgorde index"
                    ),
                ),
                (
                    "access_id",
                    rgs_django_utils.database.dj_extended_models.IntegerField(
                        blank=True, null=True, verbose_name="toegang id"
                    ),
                ),
                (
                    "warnings",
                    rgs_django_utils.database.dj_extended_models.JSONField(
                        blank=True, null=True, verbose_name="waarschuwingen"
                    ),
                ),
                (
                    "default_extent",
                    rgs_django_utils.database.dj_extended_models.ArrayField(
                        base_field=rgs_django_utils.database.dj_extended_models.FloatField(),
                        blank=True,
                        null=True,
                        size=4,
                        verbose_name="extent",
                    ),
                ),
                (
                    "access_through",
                    rgs_django_utils.database.dj_extended_models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rgs_django_utils.enumaccessthrough",
                        verbose_name="toegang via",
                    ),
                ),
            ],
            options={
                "verbose_name": "kaart",
                "verbose_name_plural": "kaart",
                "db_table": "spatial_map",
            },
        ),
        migrations.CreateModel(
            name="SpatialMapLayer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "order",
                    rgs_django_utils.database.dj_extended_models.IntegerField(default=0, verbose_name="volgorde"),
                ),
                (
                    "visible",
                    rgs_django_utils.database.dj_extended_models.BooleanField(default=True, verbose_name="zichtbaar"),
                ),
                (
                    "default_style",
                    rgs_django_utils.database.dj_extended_models.JSONField(
                        blank=True, null=True, verbose_name="standaard stijl"
                    ),
                ),
                (
                    "default_opacity",
                    rgs_django_utils.database.dj_extended_models.FloatField(
                        default=1.0, verbose_name="standaard dekking"
                    ),
                ),
                (
                    "layer",
                    rgs_django_utils.database.dj_extended_models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rgs_django_spatial.spatiallayer",
                        verbose_name="laag",
                    ),
                ),
                (
                    "map",
                    rgs_django_utils.database.dj_extended_models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rgs_django_spatial.spatialmap",
                        verbose_name="kaart",
                    ),
                ),
            ],
            options={
                "verbose_name": "kaart-kaartlaag",
                "verbose_name_plural": "kaart-kaartlagen",
                "db_table": "spatial_map_layer",
            },
        ),
        migrations.CreateModel(
            name="SpatialSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name="naam")),
                (
                    "description",
                    rgs_django_utils.database.dj_extended_models.TextStringField(
                        blank=True, null=True, verbose_name="omschrijving"
                    ),
                ),
                (
                    "source_config",
                    rgs_django_utils.database.dj_extended_models.JSONField(verbose_name="source configuratie"),
                ),
                (
                    "geojson_file",
                    rgs_django_utils.database.dj_extended_models.FileField(
                        blank=True, null=True, upload_to="spatial_sources/geojson/", verbose_name="geojson bestand"
                    ),
                ),
                (
                    "authentication_config",
                    rgs_django_utils.database.dj_extended_models.JSONField(
                        blank=True, null=True, verbose_name="authenticatie configuratie"
                    ),
                ),
                (
                    "authentication_type",
                    rgs_django_utils.database.dj_extended_models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rgs_django_spatial.enummapauthtype",
                        verbose_name="authenticatie type",
                    ),
                ),
                (
                    "source_type",
                    rgs_django_utils.database.dj_extended_models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rgs_django_spatial.enummapsourcetype",
                        verbose_name="source type",
                    ),
                ),
            ],
            options={
                "verbose_name": "kaartbron",
                "verbose_name_plural": "kaartbronnen",
                "db_table": "spatial_source",
            },
        ),
        migrations.AddField(
            model_name="spatiallayer",
            name="source",
            field=rgs_django_utils.database.dj_extended_models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="rgs_django_spatial.spatialsource",
                verbose_name="kaartbron",
            ),
        ),
        migrations.CreateModel(
            name="SpatialLayerStyle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name="naam")),
                ("order", rgs_django_utils.database.dj_extended_models.IntegerField(verbose_name="volgorde")),
                (
                    "active",
                    rgs_django_utils.database.dj_extended_models.BooleanField(
                        default=False, verbose_name="selecteerbaar"
                    ),
                ),
                (
                    "warnings",
                    rgs_django_utils.database.dj_extended_models.JSONField(
                        blank=True, null=True, verbose_name="waarschuwingen"
                    ),
                ),
                (
                    "layer",
                    rgs_django_utils.database.dj_extended_models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="styles",
                        to="rgs_django_spatial.spatiallayer",
                        verbose_name="kaartlaag",
                    ),
                ),
                (
                    "style",
                    rgs_django_utils.database.dj_extended_models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rgs_django_spatial.spatialstyle",
                        verbose_name="stijl",
                    ),
                ),
            ],
            options={
                "verbose_name": "kaartlaag stijl",
                "verbose_name_plural": "kaartlaag stijlen",
                "db_table": "spatial_layer_style",
                "ordering": ["layer", "order"],
                "constraints": [models.UniqueConstraint(fields=("layer", "style"), name="unique_layer_style")],
            },
        ),
    ]
