# Generated by Django 5.2.5 on 2025-10-23 19:41

import rgs_django_utils.database.dj_extended_models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rgs_django_spatial", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spatialmap",
            name="order_index",
        ),
        migrations.AddField(
            model_name="spatialmap",
            name="order",
            field=rgs_django_utils.database.dj_extended_models.IntegerField(default=0, verbose_name="volgorde"),
        ),
    ]
