# Generated by Django 5.2.5 on 2025-11-11 08:13

import rgs_django_utils.database.dj_extended_models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rgs_django_spatial", "0002_remove_spatialmap_order_index_spatialmap_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spatialmap",
            name="description",
            field=rgs_django_utils.database.dj_extended_models.TextField(
                blank=True, null=True, verbose_name="omschrijving"
            ),
        ),
    ]
