# Generated by Django 5.2.12 on 2026-07-02 09:35

import django.db.models.deletion
import rgs_django_utils.database.dj_extended_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgs_django_spatial', '0003_alter_spatialmap_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialTheme',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.BigAutoField(primary_key=True, serialize=False)),
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='naam')),
                ('order', rgs_django_utils.database.dj_extended_models.IntegerField(default=0, verbose_name='volgorde')),
            ],
            options={
                'verbose_name': 'kaartthema',
                'verbose_name_plural': "kaartthema's",
                'db_table': 'spatial_theme',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='spatialmaplayer',
            name='default_label_field',
            field=rgs_django_utils.database.dj_extended_models.TextStringField(blank=True, null=True, verbose_name='standaard labelveld'),
        ),
        migrations.AddField(
            model_name='spatialmaplayer',
            name='default_label_visible',
            field=rgs_django_utils.database.dj_extended_models.BooleanField(default=False, verbose_name='label standaard zichtbaar'),
        ),
        migrations.AddField(
            model_name='spatialsource',
            name='file',
            field=rgs_django_utils.database.dj_extended_models.FileField(blank=True, help_text='GeoPackage (.gpkg) of GeoJSON (.geojson) voor bestand-bronnen (tiling in fase 2).', null=True, upload_to='spatial_sources/files/', verbose_name='bestand'),
        ),
        migrations.AddField(
            model_name='spatialsource',
            name='reproject',
            field=rgs_django_utils.database.dj_extended_models.BooleanField(default=False, verbose_name='herprojecteren via MapProxy'),
        ),
        migrations.AddField(
            model_name='spatialsource',
            name='tile_fout',
            field=rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='tile foutmelding'),
        ),
        migrations.AddField(
            model_name='spatialsource',
            name='tile_status',
            field=rgs_django_utils.database.dj_extended_models.TextStringField(default='geen', verbose_name='tile status'),
        ),
        migrations.AlterField(
            model_name='spatiallayer',
            name='id',
            field=rgs_django_utils.database.dj_extended_models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spatialmaplayer',
            name='id',
            field=rgs_django_utils.database.dj_extended_models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spatialsource',
            name='id',
            field=rgs_django_utils.database.dj_extended_models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='spatialmaplayer',
            name='theme',
            field=rgs_django_utils.database.dj_extended_models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rgs_django_spatial.spatialtheme', verbose_name='thema'),
        ),
    ]
