# Generated by Django 6.0.8 on 2026-09-18 23:55

import rgs_django_utils.database.dj_extended_models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rgs_django_spatial", "0007_spatialkleurenset_uuid_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="spatiallayerstyle",
            name="modules",
            field=rgs_django_utils.database.dj_extended_models.TextStringField(
                blank=True, null=True, verbose_name="modules"
            ),
        ),
        migrations.AddField(
            model_name="spatiallayerstyle",
            name="standaard_in",
            field=rgs_django_utils.database.dj_extended_models.TextStringField(
                blank=True, null=True, verbose_name="standaard in"
            ),
        ),
    ]
