# Generated by Django 6.0.8 on 2026-09-23 07:41

import django.db.models.deletion
import rgs_django_utils.database.dj_extended_models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rgs_django_spatial", "0008_spatiallayerstyle_modules"),
        ("rgs_django_utils", "0003_enumaccessthrough"),
    ]

    operations = [
        migrations.AddField(
            model_name="spatialsource",
            name="access_id",
            field=rgs_django_utils.database.dj_extended_models.IntegerField(
                blank=True, null=True, verbose_name="toegang id"
            ),
        ),
        migrations.AddField(
            model_name="spatialsource",
            name="access_through",
            field=rgs_django_utils.database.dj_extended_models.ForeignKey(
                db_default="authenticated",
                default="authenticated",
                on_delete=django.db.models.deletion.PROTECT,
                to="rgs_django_utils.enumaccessthrough",
                verbose_name="toegang via",
            ),
        ),
        migrations.AddField(
            model_name="spatialtheme",
            name="access_id",
            field=rgs_django_utils.database.dj_extended_models.IntegerField(
                blank=True, null=True, verbose_name="toegang id"
            ),
        ),
        migrations.AddField(
            model_name="spatialtheme",
            name="access_through",
            field=rgs_django_utils.database.dj_extended_models.ForeignKey(
                db_default="authenticated",
                default="authenticated",
                on_delete=django.db.models.deletion.PROTECT,
                to="rgs_django_utils.enumaccessthrough",
                verbose_name="toegang via",
            ),
        ),
        migrations.AlterField(
            model_name="spatiallayer",
            name="access_through",
            field=rgs_django_utils.database.dj_extended_models.ForeignKey(
                db_default="authenticated",
                default="authenticated",
                on_delete=django.db.models.deletion.PROTECT,
                to="rgs_django_utils.enumaccessthrough",
                verbose_name="toegang via",
            ),
        ),
        migrations.AlterField(
            model_name="spatiallayer",
            name="name",
            field=rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name="naam"),
        ),
        migrations.AlterField(
            model_name="spatialsource",
            name="name",
            field=rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name="naam"),
        ),
        migrations.AlterField(
            model_name="spatialtheme",
            name="name",
            field=rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name="naam"),
        ),
        migrations.AddConstraint(
            model_name="spatiallayer",
            constraint=models.UniqueConstraint(
                fields=("name", "access_through", "access_id"),
                name="spatial_layer_name_per_scope",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="spatialsource",
            constraint=models.UniqueConstraint(
                fields=("name", "access_through", "access_id"),
                name="spatial_source_name_per_scope",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="spatialtheme",
            constraint=models.UniqueConstraint(
                fields=("name", "access_through", "access_id"),
                name="spatial_theme_name_per_scope",
                nulls_distinct=False,
            ),
        ),
    ]
