# Generated by Django 5.2.17 on 2026-10-03 07:25

import django.db.models.deletion
import rgs_django_utils.database.dj_extended_models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rgs_django_spatial", "0009_organisatie_scope"),
        ("rgs_django_utils", "0003_enumaccessthrough"),
    ]

    operations = [
        migrations.AddField(
            model_name="spatialkleurenset",
            name="access_id",
            field=rgs_django_utils.database.dj_extended_models.IntegerField(
                blank=True, null=True, verbose_name="toegang id"
            ),
        ),
        migrations.AddField(
            model_name="spatialkleurenset",
            name="access_through",
            field=rgs_django_utils.database.dj_extended_models.ForeignKey(
                db_default="authenticated",
                default="authenticated",
                on_delete=django.db.models.deletion.PROTECT,
                to="rgs_django_utils.enumaccessthrough",
                verbose_name="toegang via",
            ),
        ),
        migrations.AddField(
            model_name="spatialstyle",
            name="access_id",
            field=rgs_django_utils.database.dj_extended_models.IntegerField(
                blank=True, null=True, verbose_name="toegang id"
            ),
        ),
        migrations.AddField(
            model_name="spatialstyle",
            name="access_through",
            field=rgs_django_utils.database.dj_extended_models.ForeignKey(
                db_default="authenticated",
                default="authenticated",
                on_delete=django.db.models.deletion.PROTECT,
                to="rgs_django_utils.enumaccessthrough",
                verbose_name="toegang via",
            ),
        ),
    ]
